CATEGORIES = ["Social Media", "Tech", "World", "Business", "AI", "Science", "Entertainment"]

SOURCES = [
    "TechCrunch", "The Verge", "Reuters", "Bloomberg", "Mashable",
    "Wired", "Social Media Today", "The Information", "Axios", "CNBC",
    "BBC News", "The Guardian", "NYT", "WSJ", "Engadget", "Ars Technica",
    "MIT Tech Review", "Nature", "Science Daily", "Variety", "The Hollywood Reporter",
    "Forbes", "Fortune", "Financial Times", "VentureBeat",
]

TRENDING_TOPICS = [
    "#ThreadsGrowth", "#TwitterXChanges", "#MetaAI", "#TikTokBan",
    "#InstagramReels", "#LinkedInCreator", "#YouTubeShorts", "#AIContent",
    "#DigitalPrivacy", "#CreatorEconomy", "#SocialCommerce", "#BlueSky",
    "#QuantumComputing", "#ClimateTech", "#Web3", "#SpaceExploration",
    "#GenerativeAI", "#CyberSecurity", "#RemoteWork", "#DigitalNomad",
]

BREAKING_HEADS = [
    "Meta unveils AI-powered content moderation overhaul for 2026",
    "TikTok expands e-commerce integration across European markets",
    "X introduces verified organization subscriptions with revenue sharing",
    "Instagram tests AI-generated profile summaries and insights",
    "EU proposes new Digital Fairness Act targeting social platforms",
    "YouTube launches creator AI studio across all tiers",
    "Snapchat reports record quarterly revenue from AR advertising",
    "LinkedIn hits 1 billion members, rolls out AI job matching",
    "Google DeepMind achieves breakthrough in protein folding prediction",
    "NASA confirms water molecules discovered on Mars surface",
    "Global streaming market surpasses 2 billion subscribers worldwide",
    "Apple releases visionOS 3 with spatial computing enhancements",
]

BREAKING_SUMMARIES = [
    "The new system leverages large language models to identify harmful content in real-time across Facebook, Instagram, and Threads, reducing response times by 87%.",
    "The expansion brings in-app shopping to Germany, France, and Spain, partnering with local retailers and offering seller financing through TikTok Shop.",
    "The subscription bundles include verification badges, analytics, and priority support, with 40% revenue share for creators and publishers.",
    "The feature uses on-device machine learning to summarize user interests, activity patterns, and connection history into shareable profile cards.",
    "The legislation would mandate algorithmic transparency, impose fines for dark patterns, and require platforms to offer chronological feed options.",
    "The studio includes tools for script generation, voice cloning, automatic captions, and thumbnail creation, all within YouTube Studio.",
    "Snap's AR ads now reach 400M monthly active users, with major brands reporting 3x engagement compared to standard video ads.",
    "The professional network's AI system matches candidates with roles based on skill adjacency graphs rather than keyword matching.",
    "The new AlphaFold model predicts protein structures with atomic-level accuracy, accelerating drug discovery and disease research worldwide.",
    "Spectral analysis confirms liquid water reservoirs beneath the Martian surface, reigniting discussions about potential microbial life.",
    "Netflix, Disney+, and Max lead the charge as global streaming subscriptions cross 2 billion, with ad-tier plans driving growth.",
    "The latest update brings full spatial computing capabilities, including gesture-based navigation and seamless AR workspace integration.",
]

BREAKING_AUTHORS = ["Sarah Chen", "Alex Rivera", "Maya Patel", "James O'Brien", "Elena Kowalski", "David Kim", "Priya Sharma", "Marcus Thompson"]
BREAKING_SOURCES = ["Reuters", "Bloomberg", "TechCrunch", "The Verge", "Axios", "BBC News", "WSJ", "Nature"]

ARTICLE_POOL = {
    "Social Media": [
        ("Instagram expands creator monetization tools globally", "New revenue streams include subscription badges, bonus pools, and ad revenue sharing for Reels."),
        ("TikTok testing 30-minute video uploads", "The extended format challenges YouTube's dominance as creators push for longer-form content."),
        ("LinkedIn introduces AI-powered profile writing assistant", "The tool helps users optimize their experience sections with industry-specific language."),
        ("Threads reaches 300M monthly active users", "Meta's Twitter competitor sees steady growth driven by news and real-time conversation features."),
        ("Snapchat AR filters now support real-time object tracking", "The update enables brands to create interactive AR experiences tied to physical products."),
        ("X rolls out community fact-checking system", "Community Notes-style verification now applies to images and videos in addition to text."),
        ("YouTube Shorts surpasses 50B daily views", "Short-form video continues to dominate as YouTube invests in creator tools."),
        ("Pinterest adds AI shopping recommendations", "Visual search improvements allow users to find products directly from pinned images."),
        ("Discord launches monetization for server owners", "Server subscriptions and premium roles give community creators new revenue channels."),
        ("BeReal introduces group stories and events", "The authentic social platform expands beyond daily prompts with event-based sharing."),
        ("Facebook rolls out rebuilt video platform", "The redesigned video experience includes creator revenue sharing and live shopping."),
        ("Reddit introduces creator royalty program", "Users can now earn royalties on viral posts based on engagement metrics."),
        ("Telegram launches premium channel subscriptions", "Channel owners can now charge for exclusive content with revenue split."),
        ("Bluesky hits 50M users with federation rollout", "The decentralized platform opens federation to third-party servers."),
        ("Snapchat reports record revenue from AR shopping", "Brands using Snap's AR try-on tools see 94% higher purchase intent."),
        ("LinkedIn adds collaborative articles with AI summaries", "Users can co-author articles with AI-generated section suggestions."),
        ("Instagram tests AI-generated profile summaries", "On-device machine learning creates shareable profile cards."),
        ("Meta announces Horizon Worlds mobile launch", "The social VR platform expands to smartphones, bringing virtual events."),
        ("TikTok Shop expands to Latin American markets", "In-app shopping launches in Brazil, Mexico, and Argentina."),
        ("YouTube adds podcasting hub with video support", "A dedicated podcast section positions YouTube as a competitor to Spotify."),
        ("X introduces long-form posts for premium subscribers", "Subscribers can publish posts up to 25,000 characters."),
        ("Pinterest reports surge in visual search usage", "AI-powered camera search sees 200% year-over-year growth."),
        ("WhatsApp rolls out community chat features", "Enhanced community tools include admin controls and announcement channels."),
        ("Signal introduces usernames, removing phone number requirement", "Username-based contact discovery with end-to-end encryption."),
        ("Reddit reaches 1 billion monthly visits", "Content licensing deals with AI companies drive revenue growth."),
        ("LinkedIn launches AI-powered job matching", "Skill adjacency graphs match candidates to roles more accurately."),
    ],
    "Tech": [
        ("Google reveals Gemini 3 with real-time multimodal capabilities", "The new model processes video, audio, and text simultaneously with near-human reasoning."),
        ("Apple partners with OpenAI for on-device AI", "Siri enhancements leverage GPT-5 for complex queries with on-device privacy."),
        ("Microsoft Fabric gets unified data governance layer", "The update simplifies enterprise data management across Azure, AWS, and GCP."),
        ("Amazon launches quantum computing cloud service", "Braket Enterprise offers hybrid classical-quantum workloads for financial modeling."),
        ("NVIDIA announces next-gen GPU architecture", "Rubin architecture promises 4x AI performance gains for data center workloads."),
        ("OpenAI introduces GPT-5 with trillion-parameter capacity", "The model demonstrates significant improvements in reasoning and math."),
        ("Tesla's Optimus robot enters limited production", "The humanoid robot begins deployment in manufacturing facilities."),
        ("SpaceX Starship completes first orbital refueling", "The milestone enables deep-space missions for NASA's Artemis program."),
        ("Adobe adds generative AI to Photoshop and Illustrator", "Firefly-powered tools allow designers to generate vector graphics from prompts."),
        ("Qualcomm unveils Snapdragon X Gen 3", "The chip brings desktop-class performance with on-device AI acceleration."),
        ("Samsung demonstrates solid-state battery breakthrough", "New battery technology offers 600-mile range with 10-minute charging."),
        ("Cloud infrastructure spending reaches $330B annually", "AWS, Azure, and GCP continue rapid growth as enterprises migrate AI workloads."),
        ("Intel announces 1.4nm process technology", "The new fabrication process promises 20% better performance and 30% lower power."),
        ("AMD launches Instinct MI400 AI accelerator", "The GPU targets LLM training with 288GB HBM4 memory."),
        ("Google demonstrates quantum error correction breakthrough", "The Willow chip achieves exponential error reduction."),
        ("Apple reveals M4 Ultra with 256GB unified memory", "The chip targets AI workloads with 32-core CPU and 160-core GPU."),
        ("Microsoft announces Copilot+ PC ecosystem", "New hardware standard includes dedicated NPUs with 40+ TOPS."),
        ("Meta releases open-source Llama 4 model", "The 405B parameter model matches GPT-5 on reasoning tasks."),
        ("Raspberry Pi launches compute module for industrial use", "The CM5 offers server-grade performance in a compact form factor."),
        ("Oracle expands multi-cloud database services", "New features allow seamless data replication across AWS, Azure, and GCP."),
        ("IBM demonstrates 1,000+ qubit quantum processor", "The Condor processor marks a milestone in quantum computing."),
        ("TSMC breaks ground on 3nm chip fab in Arizona", "The $40B facility will produce advanced chips for US customers."),
        ("GitHub introduces AI-powered code review", "Copilot automatically detects security vulnerabilities and performance issues."),
        ("Spotify unveils AI DJ with real-time commentary", "The personalized DJ generates spoken track introductions between songs."),
        ("Zoom adds AI companion for meeting summarization", "The feature generates meeting notes and action items automatically."),
        ("Cloudflare launches zero-trust network platform", "The SASE platform combines SD-WAN with secure web gateway."),
    ],
    "World": [
        ("Global climate summit reaches landmark emissions agreement", "195 nations commit to 60% reduction in carbon emissions by 2035."),
        ("EU digital euro project enters pilot phase", "The central bank digital currency aims to provide privacy-preserving payments."),
        ("Japan launches world's fastest supercomputer for climate modeling", "The system performs 2.5 exaflops for climate change simulation."),
        ("India surpasses China in renewable energy capacity additions", "Solar and wind installations reach record 85GW in the fiscal year."),
        ("UN adopts treaty on AI governance and ethics", "The framework establishes binding principles for autonomous weapons."),
        ("Brazil passes landmark data sovereignty law", "Companies must store and process citizen data within national borders."),
        ("South Korea leads in 6G network testing", "Prototype networks achieve 100Gbps speeds in urban testbeds."),
        ("African Union launches continental digital ID system", "The system provides identity access to 400 million unbanked adults."),
        ("UK opens first commercial fusion power plant", "The plant produces 150MW of clean energy from nuclear fusion."),
        ("Australia bans social media for under-16", "Legislation imposes fines up to $50M on platforms failing age verification."),
        ("Singapore launches smart nation 2.0 initiative", "The plan includes nationwide AI sensors and autonomous public transport."),
        ("Arctic research station detects unprecedented ice melt patterns", "Scientists report 40% faster ice loss than predicted."),
        ("Germany commits $500B to green hydrogen infrastructure", "The investment targets 10GW electrolysis capacity by 2030."),
        ("China launches first commercial space station module", "The Tiangong station enables expanded microgravity research."),
        ("Canada implements universal pharmacare program", "The national program covers essential medications for all citizens."),
        ("Kenya leads African tech innovation with silicon savannah", "Nairobi's tech ecosystem attracts $2B in venture funding."),
        ("France enacts right-to-repair legislation for electronics", "Manufacturers must provide repair manuals for seven years."),
        ("UAE launches Mars colony simulation project", "The year-long analog mission tests human resilience for Mars habitats."),
        ("Indonesia moves capital to Nusantara in Borneo", "The new smart city features AI-managed traffic and 100% renewable energy."),
        ("Switzerland approves nation-wide digital identity system", "The blockchain-based system gives citizens control over personal data."),
        ("New Zealand passes climate adaptation fund legislation", "The fund supports communities relocating from flood-prone zones."),
        ("Saudi Arabia opens NEOM smart city first phase", "The linear city features AI-managed utilities and autonomous transport."),
        ("Mexico legalizes psychedelic-assisted therapy", "The framework allows controlled therapeutic use for mental health."),
        ("Nordic countries launch joint quantum computing initiative", "Five countries commit $1.5B to build shared quantum infrastructure."),
        ("Antarctic research station discovers ancient ecosystem", "Microbial life found in subglacial lake sediments."),
        ("WHO declares mental health a global health priority", "Member states commit to increasing mental health funding to 10%."),
    ],
    "Business": [
        ("Creator economy valued at $480B in 2026", "85 million creators globally diversify across platforms."),
        ("Digital advertising spend surpasses $800B annually", "Social media ads account for 42% of digital ad spending."),
        ("Streaming wars intensify with bundled offerings", "Disney, Warner, and Netflix offer discounted bundles."),
        ("Venture capital funding rebounds in Q2 2026", "AI startups capture 45% of all VC funding."),
        ("Retail media networks emerge as third-wave advertising", "Walmart, Amazon, and Target ad businesses grow 35% YoY."),
        ("ESG investing reaches $50T in assets under management", "Climate-tech leads as greenwashing penalties increase."),
        ("Remote work permanently reshapes commercial real estate", "Office occupancy stabilizes at 40% of pre-pandemic levels."),
        ("Central banks explore retail CBDC implementations", "Eleven countries launch pilot programs for digital currencies."),
        ("Gaming industry revenue hits $250B annually", "Mobile gaming leads at 52% share."),
        ("Subscription economy expands beyond media", "65% of consumers globally use subscription models."),
        ("M&A activity surges in tech sector", "Deal volume reaches $1.2T in H1 2026."),
        ("Supply chain AI optimization saves $150B", "Companies report 30% reduction in logistics costs."),
        ("Stripe valuation reaches $150B in secondary markets", "Payment processor revenue grows 40% annually."),
        ("Electric vehicle sales reach 40% of new car market", "Price parity with ICE vehicles drives mass adoption."),
        ("Private equity firms raise record $1.5T in dry powder", "Record capital signals increased buyout activity."),
        ("SaaS companies embrace usage-based pricing", "Companies report 30% higher retention with consumption billing."),
        ("Bioprinting organ startups attract $5B in investments", "3D-printed tissues move from research to clinical trials."),
        ("Fintech lending reaches $500B in annual originations", "Alternative lenders capture 25% of consumer lending."),
        ("Space economy grows to $500B", "Satellite internet and space tourism drive growth."),
        ("Insurance tech startups disrupt $6T industry", "AI underwriting reduces operational costs by 40%."),
        ("Food delivery platforms achieve profitability", "DoorDash and Uber Eats report first profitable quarters."),
        ("Biotech IPO market recovers with $30B in new listings", "Gene therapy and mRNA companies lead the resurgence."),
    ],
    "AI": [
        ("Claude 5 demonstrates artificial general intelligence capabilities", "The model achieves human-level performance on 95% of cognitive benchmarks."),
        ("AI-generated content labeling becomes mandatory", "Major platforms implement automatic detection of synthetic media."),
        ("Deepfake detection technology reaches 99.9% accuracy", "New models analyze sub-pixel consistency patterns."),
        ("AI regulation frameworks adopted by 40 countries", "International AI Governance Council establishes safety testing."),
        ("Generative AI in healthcare receives FDA approval", "AI diagnostics reduced diagnosis time by 80%."),
        ("Autonomous AI agents enter enterprise workflows", "Companies report 60% productivity gains from AI agents."),
        ("AI energy consumption becomes environmental concern", "Data centers consume 4% of global electricity."),
        ("Open-source AI models challenge proprietary systems", "Llama 4 and Mistral 3 match GPT-5 on key benchmarks."),
        ("AI in education personalizes learning at scale", "Adaptive tutoring systems show 40% improvement in outcomes."),
        ("AI assistants gain persistent memory and personalization", "Next-gen assistants remember preferences across sessions."),
        ("Robotics AI achieves breakthrough in dexterous manipulation", "Humanoid robots handle unfamiliar objects with precision."),
        ("AI discovers new antibiotic class", "ML models identify novel antibiotics effective against superbugs."),
        ("Computer vision surpasses human accuracy in medical imaging", "AI detects 50+ conditions across X-ray, MRI, and CT scans."),
        ("AI-powered drug discovery cuts development time by 60%", "ML predicts drug-target interactions in weeks."),
        ("NLP achieves human parity in translation", "AI matches professional translators across 100+ language pairs."),
        ("AI art generators face copyright lawsuits", "Class action suits argue training on copyrighted images violates rights."),
        ("Reinforcement learning optimizes energy grid management", "AI systems reduce energy waste by 25% across national grids."),
        ("Autonomous vehicles reach level 5 in controlled environments", "Self-driving taxis operate in 15 cities without safety drivers."),
        ("AI predicts protein structures for 200 million proteins", "DeepMind and Meta release databases covering virtually all proteins."),
        ("Emotion AI systems enter customer service", "Affective computing improves support outcomes by 35%."),
        ("Synthetic data generation transforms AI training", "AI-generated training data reduces collection costs by 80%."),
        ("Federated learning enables privacy-preserving collaboration", "Hospitals train models without exposing sensitive data."),
        ("AI chip market reaches $200B in annual revenue", "Specialized AI processors drive a new computing era."),
        ("Explainable AI becomes regulatory requirement", "AI must provide human-understandable explanations for decisions."),
        ("AI weather forecasting outperforms traditional models", "GraphCast predicts extreme weather 7 days ahead with 99% accuracy."),
        ("Multimodal AI enables cross-modal content generation", "Models generate cohesive multi-format content from single prompts."),
    ],
    "Science": [
        ("CERN discovers new particle beyond Standard Model", "The LHC reveals a previously unknown particle that could explain dark matter."),
        ("NASA's James Webb detects atmosphere on exoplanet", "JWST identifies water vapor on a habitable-zone exoplanet."),
        ("CRISPR gene therapy approved for sickle cell disease", "The first CRISPR treatment shows 95% success rate."),
        ("Quantum entanglement demonstrated at room temperature", "Researchers eliminate a major barrier to practical quantum networks."),
        ("Ocean cleanup removes 100,000 tons of plastic", "AI-guided autonomous vessels clean the Great Pacific Garbage Patch."),
        ("Mars rover discovers organic molecules", "Perseverance finds complex compounds in Jezero Crater."),
        ("Lab-grown meat receives FDA approval for retail sale", "Cultivated chicken and beef hit grocery store shelves."),
        ("New battery achieves 1,000 Wh/kg density", "Lithium-sulfur batteries enable 1,000-mile EV range."),
        ("Gene editing eliminates HIV in animal trials", "CRISPR therapy removes latent HIV from infected cells."),
        ("Deep ocean expedition discovers new ecosystem", "Hydrothermal vent community reveals species adapted to extreme pressure."),
        ("Solar panel efficiency reaches 50% breakthrough", "Multi-junction perovskite-silicon cells make solar cheaper than fossil fuels."),
        ("Brain-computer interface restores speech", "Implantable decoders translate brain signals at 60 words per minute."),
        ("Antarctic ice core reveals 1 million years of climate data", "The oldest ice core provides insights into Earth's climate cycles."),
        ("Artificial photosynthesis achieves 20% efficiency", "The bio-inspired system converts CO2 into liquid fuel."),
        ("Microplastics found in human brain tissue", "Study raises urgent questions about health impacts."),
        ("Nuclear fusion sustains plasma for record 30 minutes", "EAST tokamak brings commercial fusion closer."),
        ("New antibiotic discovered in deep sea sponges", "Spongicidin shows effectiveness against MRSA."),
        ("Lunar telescope detects cosmic rays from deep space", "Far-side radio observatory reveals new particle physics."),
        ("Self-healing materials developed for infrastructure", "Concrete with healing agents extends building lifespan by 50%."),
    ],
    "Entertainment": [
        ("Netflix announces interactive AI-powered movie experience", "Viewers influence plot directions through voice commands."),
        ("Taylor Swift breaks streaming record with 500M first-day plays", "Her album breaks all previous platform records."),
        ("Virtual reality concerts attract 50 million viewers", "Fortnite and Roblox host simultaneous VR concerts."),
        ("Streaming services invest $50B in original content for 2026", "Netflix, Amazon, Apple, and Disney commit record budgets."),
        ("AI-generated movies debut at international film festival", "The first feature-length AI film premieres at Cannes."),
        ("Gaming embraces cloud-native development", "New titles stream directly to browsers with console-quality graphics."),
        ("Music industry adopts blockchain for royalty payments", "Smart contracts distribute royalties in real-time."),
        ("YouTube introduces revenue sharing for short-form creators", "Shorts creators earn ad revenue share."),
        ("Anime streaming market grows to $20B annually", "Global viewership surges 80% outside Japan."),
        ("Podcast industry reaches $10B in advertising revenue", "AI-powered dynamic ad insertion drives monetization."),
        ("E-sports tournaments offer $100M prize pools", "League of Legends and Valorant set record prize pools."),
        ("AR glasses for entertainment hit mass market", "Lightweight glasses under $300 bring holographic displays."),
        ("Hollywood adopts virtual production for major films", "LED wall stages reduce post-production time by 40%."),
        ("Spotify launches AI music generator", "Users generate custom songs in their favorite artists' style."),
        ("Theme parks integrate mixed reality attractions", "AR headsets transform rides into interactive experiences."),
        ("Book publishing sees AI-assisted authorship boom", "AI-assisted authors account for 30% of bestseller lists."),
        ("TikTok expands to 60-minute video uploads", "The platform moves into long-form content."),
        ("Classic film restoration using AI achieves 4K quality", "ML upscales and colorizes 100 classic films."),
        ("Social audio platforms revive with AI moderation", "AI enables safe real-time audio conversations."),
        ("Indie game development boom continues with AI tools", "AI-assisted design enables solo developers to create AAA-quality games."),
    ],
}

LIVE_FEED_TEMPLATES = [
    ("{s}: {t} trending with {p}% engagement surge", ["TechCrunch", "The Verge", "Mashable"], ["#ThreadsGrowth", "#AI", "#TikTok", "#Meta", "#Instagram"]),
    ("Report: {p}% of marketers boost {t} budget", ["Social Media Today", "eMarketer"], ["social video", "influencer marketing", "paid social", "UGC"]),
    ("{s}: {t} partners with {t2}", ["Bloomberg", "Reuters"], ["Meta", "TikTok", "Google", "Snap", "Microsoft", "Amazon"]),
    ("Breaking: {t} acquires {t2} for ${v}B", ["Axios", "The Information"], ["OpenAI", "Stripe", "Discord", "Pinterest", "Reddit", "Spotify"]),
    ("{t} launches new {t2} features", ["TechCrunch", "The Verge"], ["Instagram", "LinkedIn", "X", "YouTube", "Snapchat", "TikTok"]),
    ("{s} reports {p}% revenue growth in {t} segment", ["Bloomberg", "CNBC", "Reuters"], ["cloud", "advertising", "AI", "streaming", "gaming"]),
    ("{t} stock surges {p}% on {t2} announcement", ["WSJ", "Bloomberg", "CNBC"], ["NVIDIA", "Apple", "Meta", "Amazon", "Tesla", "Netflix"]),
    ("{s}: {p}M users join {t} this week", ["The Verge", "Mashable", "TechCrunch"], ["Bluesky", "Threads", "Signal", "Telegram", "LinkedIn"]),
    ("Regulator investigates {t} over {t2} practices", ["Reuters", "BBC News"], ["Meta", "Google", "TikTok", "X", "Amazon"]),
    ("{t} reaches {p}M daily active users milestone", ["TechCrunch", "Axios"], ["ChatGPT", "Copilot", "Gemini", "Claude", "Perplexity"]),
]

CAT_ICONS = {
    "Social Media": "\U0001f4f1", "Tech": "\U0001f4bb", "World": "\U0001f30d",
    "Business": "\U0001f4ca", "AI": "\U0001f916", "Science": "\U0001f52c", "Entertainment": "\U0001f3ac",
}

CAT_COLORS = {
    "Social Media": "#8b5cf6", "Tech": "#0ea5e9", "World": "#34d399",
    "Business": "#f59e0b", "AI": "#ec4899", "Science": "#14b8a6", "Entertainment": "#f97316",
}